#!/usr/bin/env bash
set -Eeuo pipefail

# One-command macOS bootstrap for the local WebUI deployment.
#
# Usage:
#   ./macos-deploy.sh              # install/update dependencies and start WebUI
#   ./macos-deploy.sh update       # fast-forward the required branch, then start
#   ./macos-deploy.sh start        # start using the existing environment
#   ./macos-deploy.sh restart      # restart WebUI
#   ./macos-deploy.sh status       # show WebUI status
#   ./macos-deploy.sh logs         # follow WebUI logs
#   ./macos-deploy.sh stop         # stop WebUI

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

EXPECTED_BRANCH="${EXPECTED_GIT_BRANCH:-codex/long-term-platform-foundation}"
VENV_DIR="${VENV_DIR:-$ROOT_DIR/.venv}"
OPEN_BROWSER="${OPEN_BROWSER:-1}"
PORT="${PORT:-5000}"
SKIP_FRONTEND_BUILD="${SKIP_FRONTEND_BUILD:-0}"
SKIP_PLAYWRIGHT_INSTALL="${SKIP_PLAYWRIGHT_INSTALL:-0}"

log() {
  printf '[macOS部署] %s\n' "$*"
}

die() {
  printf '[macOS部署] 错误：%s\n' "$*" >&2
  exit 1
}

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

ensure_macos() {
  [[ "$(uname -s)" == "Darwin" ]] || die "此脚本只支持 macOS；Linux/Windows 请使用 docs/deployment.md 中对应方案。"
}

load_homebrew() {
  if command_exists brew; then
    eval "$(brew shellenv)"
    return
  fi

  local brew_path=""
  if [[ -x /opt/homebrew/bin/brew ]]; then
    brew_path=/opt/homebrew/bin/brew
  elif [[ -x /usr/local/bin/brew ]]; then
    brew_path=/usr/local/bin/brew
  fi

  if [[ -n "$brew_path" ]]; then
    eval "$("$brew_path" shellenv)"
    return
  fi

  if [[ "${INSTALL_HOMEBREW:-1}" != "1" ]]; then
    die "未找到 Homebrew。请安装 Homebrew，或设置 INSTALL_HOMEBREW=1 后重试。"
  fi

  log "未找到 Homebrew，开始安装（可能需要输入 macOS 管理员密码）"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  if [[ -x /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  elif [[ -x /usr/local/bin/brew ]]; then
    eval "$(/usr/local/bin/brew shellenv)"
  else
    die "Homebrew 安装后仍未找到 brew 命令。"
  fi
}

ensure_tools() {
  local missing=()
  command_exists git || missing+=(git)
  command_exists python3 || missing+=(python)
  command_exists node || missing+=(node)
  if ((${#missing[@]})); then
    log "安装缺失工具：${missing[*]}"
    brew install "${missing[@]}"
  fi

  command_exists git || die "git 命令不可用。"
  command_exists python3 || die "python3 命令不可用。"
  command_exists node || die "node 命令不可用。"
}

check_branch() {
  local branch
  branch="$(git branch --show-current 2>/dev/null || true)"
  [[ "$branch" == "$EXPECTED_BRANCH" ]] || die "当前分支为 ${branch:-<detached>}，请切换到 ${EXPECTED_BRANCH}。"
}

update_branch() {
  check_branch
  log "同步 ${EXPECTED_BRANCH}"
  git fetch origin "$EXPECTED_BRANCH"
  git pull --ff-only origin "$EXPECTED_BRANCH"
}

setup_python() {
  if [[ ! -x "$VENV_DIR/bin/python" ]]; then
    log "创建 Python 虚拟环境：$VENV_DIR"
    python3 -m venv "$VENV_DIR"
  fi
  "$VENV_DIR/bin/python" -m pip install --upgrade pip
  "$VENV_DIR/bin/python" -m pip install -r requirements.txt

  if [[ "$SKIP_PLAYWRIGHT_INSTALL" != "1" ]]; then
    "$VENV_DIR/bin/python" -m playwright install chromium
  fi
}

setup_frontend() {
  [[ "$SKIP_FRONTEND_BUILD" == "1" ]] && return
  [[ -f frontend/package.json ]] || return
  log "构建前端静态资源"
  (cd frontend && npm install --no-audit --no-fund && npm run build)
}

ensure_env() {
  if [[ ! -f .env ]]; then
    cp .env.example .env
    log "已从 .env.example 创建 .env"
  fi

  "$VENV_DIR/bin/python" - <<'PY'
from pathlib import Path
import secrets

path = Path('.env')
text = path.read_text(encoding='utf-8')
lines = text.splitlines()
keys = {'WEBUI_AUTH_CODE', 'AUTH_CODE', 'WEB_AUTH_CODE'}
auth_value = ''
webui_line_index = None
out = []
for line in lines:
    stripped = line.lstrip()
    key = stripped.split('=', 1)[0].strip() if '=' in stripped and not stripped.startswith('#') else ''
    if key in keys:
        value = line.split('=', 1)[1].strip().strip('"\'')
        if value and not auth_value:
            auth_value = value
        if key == 'WEBUI_AUTH_CODE' and webui_line_index is None:
            webui_line_index = len(out)
            out.append(line)
        continue
    out.append(line)

if not auth_value:
    code = secrets.token_urlsafe(18)
    replacement = f'WEBUI_AUTH_CODE="{code}"'
    if webui_line_index is not None:
        out[webui_line_index] = replacement
    else:
        if out and out[-1].strip():
            out.append('')
        out.extend(['# ---- generated by macos-deploy.sh ----', replacement])
    path.write_text('\n'.join(out).rstrip() + '\n', encoding='utf-8')
    print(f'[macOS部署] 已生成 WEBUI_AUTH_CODE，长度={len(code)}；可用 grep 查看。')
else:
    print('[macOS部署] 已保留现有 WEBUI_AUTH_CODE。')
PY
}

start_webui() {
  log "启动 WebUI：http://127.0.0.1:${PORT}"
  PORT="$PORT" OPEN_BROWSER="$OPEN_BROWSER" "$ROOT_DIR/webui.sh" restart
  log "授权码查看：grep -E '^(WEBUI_AUTH_CODE|AUTH_CODE|WEB_AUTH_CODE)=' .env"
}

bootstrap() {
  ensure_macos
  load_homebrew
  ensure_tools
  check_branch
  ensure_env
  setup_python
  setup_frontend
  start_webui
}

usage() {
  sed -n '1,18p' "$0"
  cat <<'HELP'

环境变量：
  OPEN_BROWSER=0        启动后不自动打开浏览器
  PORT=5000              修改本机 WebUI 端口
  SKIP_FRONTEND_BUILD=1  跳过 npm 构建
  SKIP_PLAYWRIGHT_INSTALL=1  跳过 Chromium 安装
  INSTALL_HOMEBREW=0     Homebrew 缺失时只提示，不自动安装
HELP
}

case "${1:-}" in
  ''|bootstrap|install) bootstrap ;;
  update) ensure_macos; load_homebrew; ensure_tools; update_branch; ensure_env; setup_python; setup_frontend; start_webui ;;
  start) ensure_macos; PORT="$PORT" OPEN_BROWSER="$OPEN_BROWSER" "$ROOT_DIR/webui.sh" start ;;
  restart) ensure_macos; PORT="$PORT" OPEN_BROWSER="$OPEN_BROWSER" "$ROOT_DIR/webui.sh" restart ;;
  status|logs|stop) ensure_macos; PORT="$PORT" "$ROOT_DIR/webui.sh" "$1" ;;
  -h|--help|help) usage ;;
  *) die "未知命令：$1；使用 ./macos-deploy.sh --help 查看用法。" ;;
esac
